server:
  port: 8082
  
spring:  application:    name: DC-SERVICE
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dc
    username: root
    password: Jairam@84
    
  jpa:    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:      ddl-auto: update
    show-sql: true
      boot:    admin:      client:        url: http://localhost://1111/

management:  endpoints:    web:      exposure:        include: '*'        